version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - blog_content:/web/blog
      - acme_data:/web/acme/data
    volumes_from:
      - site:ro
      - piwik:ro
      # - adminer:ro
    links:
      - site
      - blog
      - piwik
      - kgb
      # - adminer
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  site:
    build:
      context: .
      dockerfile: ./site/Dockerfile
    volumes:
      - /web/site
      - kivy_docs:/web/docs
      - downloads:/web/downloads
    ports:
      - 2457:2457
    env_file:
      - ./secrets/env/site
    logging:
      <<: *logging

  kgb:
    build:
      context: ./kgb
    env_file:
      - ./secrets/env/kgb
    logging:
      <<: *logging

  blog:
    build:
      context: ./blog
    volumes:
      - blog_content:/web/blog
    links:
      - mysql
    logging:
      <<: *logging

  piwik:
    build:
      context: ./piwik
    links:
      - mysql
    logging:
      <<: *logging

  mysql:
    build:
      context: ./mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./secrets/env/mysql
    logging:
      <<: *logging

  nocarrier:
    build:
      context: ./nocarrier
    env_file:
      - ./secrets/env/nocarrier
    logging:
      <<: *logging

  # adminer:
  #   build:
  #     context: ./adminer
  #   volumes:
  #     - /adminer
  #   links:
  #     - mysql
  #   logging:
  #     <<: *logging

volumes:
  blog_content:
  mysql_data:
  acme_data:
  kivy_docs:
  downloads:
